package com.sv.constants;

public interface StatusConstants {
	String VERIFY_FAILED = "VERIFY_FAILED";
	String VERIFY_SUCCESS = "VERIFY_SUCCESS";
	String SCHOOL_CREATION_FAILED = "SCHOOL_CREATION_FAILED";
	String SCHOOL_CREATION_SUCCESS = "SCHOOL_CREATION_SUCCESS";
	String SCHOOLS_NOT_FOUND = "SCHOOL_NOT_FOUND";
	String SCHOOLS_FOUND = "SCHOOL_FOUND";
	String SYSTEM_ERROR = "SYSTEM_ERROR";
	String COUNTRIES_NOT_FOUND = "COUNTRIES_NOT_FOUND";
	String COUNTRIES_FOUND = "COUNTRIES_FOUND";
	String LANGUAGES_NOT_FOUND = "LANGUAGES_NOT_FOUND";
	String LANGUAGES_FOUND = "COUNTRIES_FOUND";
	String CREATION_FAILED = "CREATION_FAILED";
	String CREATION_SUCCESS = "CREATION_SUCCESS";
	String UPDATE_SUCCESS = "UPDATE_SUCCESS";
	String UPDATE_FAILED = "UPDATE_FAILED";
	String SCHOOL_REG_FAILED = "SCHOOL_REG_FAILED";
	String SCHOOL_REG_SUCCESS = "SCHOOL_REG_SUCCESS";
	String SCHOOL_ACT_FAILED = "SCHOOL_ACT_FAILED";
	String SCHOOL_ACT_SUCCESS = "SCHOOL_ACT_SUCCESS";
	String SCHOOL_UPDATE_FAILED = "SCHOOL_UPDATE_FAILED";
	String SCHOOL_UPDATE_SUCCESS = "SCHOOL_UPDATE_SUCCESS";
	String CONSTANTS_NOT_FOUND = "CONSTANTS_NOT_FOUND";
	String CONSTANTS_FOUND = "CONSTANTS_FOUND";
	String ROLES_FOUND = "ROLES_FOUND";
	String NO_ROLES_FOUND = "NO_ROLES_FOUND";
	String USER_ALREADY_EXISTS_WITH_MOBILE_EMAIL = "USER_ALREADY_EXISTS_WITH_MOBILE_EMAIL";
	String CUST_ALREADY_EXISTS_WITH_MOBILE = "CUST_ALREADY_EXISTS_WITH_MOBILE";

}
